### ISSUE TITLE
OSX Docker containers stop working after restarting them

### ISSUE THREAD

**Issue by thinking-aloud** [docker/toolbox#442]
Hi,
I have a docker container with tomcat and after stoping and starting the container 3 times the tomcat won't work anymore. 
It starts but the tomcat is not accessible anymore and the startup logs look normal. Removing the container and even Image does not fix it. I have to completely reinstall docker to make it work again, just to have the same problem again after a couple tries.
My Linux machine does not have this issue.

I did some testing and came up with the following docker-compose file:
```
eureka:
    image: netflixoss/eureka:1.3.1
    ports: 
        - 8080:8080

eureka2:
    image: springcloud/eureka
    ports: 
        - 8181:8761

tomcat:
    image: tomcat
    links:
        - eureka
    ports: 
        - 8282:8080
```

I can start this and after like 5 sec, I have a GUI on:
- 192.168.99.100:8080/eureka
- 192.168.99.100:8181/
- 192.168.99.100:8282/

If I restart the compose file like 3 times it won't start anymore.
doing `docker-compose rm` and `docker-compose up` does not help.
The containers start, and I can ping the eureka container from the tomcat container, since they are linked. Using curl to connect to it does not work.

My system:
- OSX EL Capitan (10.11.3)
- docker toolbox 1.10.2

Docker machine ressources:
- 6 CPU cores
- 20GB RAM
- 100GB SSD

As far as I see it, this has to be some serious bug just effecting OSX. Maybe related to the network stack.

Ps. I can not get any work done since two days, so some advice, fix or workaround would be appreciated.

greetings

edit: After waiting about half an hour the containers came back.
