### ISSUE TITLE
docker-compose 1.11.1 fails to create a service on windows 7

### ISSUE THREAD

**Issue by dargoan** [docker/toolbox#631]
**Expected behavior**

I would like that "docker-compose run --rm -w /var/www/html app composer install" actually runs so that the command I try to pass as argument can run.

**Actual behavior**

Instead, I have: ERROR: Cannot create container for service app: the working directory 'C:/Program Files/Git/var/www/html' is invalid, it needs to be an absolute path.

**Information**

I'm on Windows 7. I have docker-compose version 1.11.1, installed with latest version of the Docker Toolbox.
I also tried different things, such as putting an absolute path, in the volume information, instead of ".", as the message suggested.
But I don't understand why Docker talks about Git.

This docker-compose.yml file refers to the Dockerfile bellow :

```
FROM ubuntu:16.04

MAINTAINER Johan Chouquet

RUN locale-gen en_US.UTF-8

ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

RUN apt-get update \
    && apt-get install -y nginx curl zip unzip git software-properties-common supervisor sqlite3 \
    && add-apt-repository -y ppa:ondrej/php \
    && apt-get update \
    && apt-get install -y php7.0-fpm php7.0-cli php7.0-mcrypt php7.0-gd php7.0-mysql \
       php7.0-pgsql php7.0-imap php-memcached php7.0-mbstring php7.0-xml php7.0-curl \
       php7.0-sqlite3 php7.0-xdebug \
    && php -r "readfile('http://getcomposer.org/installer');" | php -- --install-dir=/usr/bin/ --filename=composer \
    && mkdir /run/php \
    && apt-get remove -y --purge software-properties-common \
    && apt-get -y autoremove \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
    && echo "daemon off;" >> /etc/nginx/nginx.conf

RUN ln -sf /dev/stdout /var/log/nginx/access.log \
    && ln -sf /dev/stderr /var/log/nginx/error.log

COPY default /etc/nginx/sites-available/default

COPY php-fpm.conf /etc/php/7.0/fpm/php-fpm.conf

EXPOSE 81

COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

CMD ["/usr/bin/supervisord"]
```

And the docker-compose.yml file :

```
version: '2'
services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    image: johanchouquet/app
    volumes:
     - .:/var/www/html
    ports:
     - "80:80"
    networks:
     - sdnet
  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    image: johanchouquet/node
    volumes:
     - .:/var/www/html
    networks:
     - sdnet
  mysql:
    image: mysql:5.7
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "homestead"
      MYSQL_USER: "homestead"
      MYSQL_PASSWORD: "secret"
    volumes:
     - mysqldata:/var/lib/mysql
    networks:
     - sdnet
  redis:
    image: redis:alpine
    volumes:
     - redisdata:/data
    networks:
     - sdnet
networks:
  sdnet:
    driver: "bridge"
volumes:
  mysqldata:
    driver: "local"
  redisdata:
    driver: "local"
```

Is it an actual bug or something is wrong in my config or env ?

More info: after some days, i tried downgrading to toolbox 1.12.3 with docker-compose 1.8.1. Didn't change the result.
Is there a workaround ? Upgrading to Windows 10 ? If so, is it certain that it works on Windows 10 ?

Thanks a lot.
