### ISSUE TITLE
Docker compose 

### ISSUE THREAD

**Issue by marcospgp** [docker/toolbox#796]
I'm using docker toolbox on my laptop because it doesn't support docker for windows.

Our docker configuration works fine on my desktop, but when using docker toolbox I run into an issue where the volume mounted with the project files is empty.

Kitematic shows "local folder: no folder" under volume settings for both `usr/src/app` and `usr/src/app/node_modules`. While this is expected for the node_modules folder, app should be linked to the project folder on the host.

Here is the docker-compose file:

```
version: '3'
services:

  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      MONGODB_URI: mongodb://admin:paw@mongo:27017/paw?authSource=admin
    volumes:
      - .:/usr/src/app
      # More info on the node_modules volume at:
      # http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
      # under "The node_modules Volume Trick"
      - /usr/src/app/node_modules
    # Run nodemon with legacy watch
    # https://github.com/remy/nodemon#application-isnt-restarting
    command: ./node_modules/.bin/nodemon --legacy-watch --inspect=0.0.0.0:5858
    depends_on:
      - mongo

  mongo:
    image: mongo:4.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: paw
    volumes:
      # Using a named volume because windows doesn't deal well with mounting local folders
      - paw-api-mongodb-storage:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: paw
    depends_on:
      - mongo

volumes:
  # Database named module has to be declared globally
  paw-api-mongodb-storage:

```

and here is the Dockerfile:

```
FROM node:8.12.0-alpine

# Set app directory
WORKDIR /usr/src/app

# Install git in order to allow installing
# npm packages from Github
RUN set -xe \
    && apk add --no-cache git

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install

# Bundle app source
COPY . .

ENV NODE_ENV development

EXPOSE 8080

CMD ["npm","start"]

```

When I run `docker-compose up`, nodemon doesn't work because it can't find any files. It reports:

```
web_1            |   Usage: nodemon [nodemon options] [script.js] [args]
web_1            |
web_1            |   See "nodemon --help" for more.
```
