### ISSUE TITLE
file Operation not permitted

### ISSUE THREAD

**Issue by ztj1993** [docker/toolbox#861]
```
version: "2"
services:

  postgresql:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    volumes:
      - /c/Users/postgresql:/var/lib/postgresql/data:rw
```

```
fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default timezone ... UTC
selecting dynamic shared memory implementation ... posix
creating configuration files ... ok
LOG:  could not link file "pg_xlog/xlogtemp.25" to "pg_xlog/000000010000000000000001": Operation not permitted
FATAL:  could not open file "pg_xlog/000000010000000000000001": No such file or directory
child process exited with exit code 1
initdb: removing contents of data directory "/var/lib/postgresql/data"
running bootstrap script ... 
```
